name: Detect and CI - Vue App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detect-vue:
    name: Detect Vue App
    runs-on: ubuntu-latest
    outputs:
      is-vue: ${{ steps.check.outputs.is-vue }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if Vue project
        id: check
        run: |
          echo "Checking for Vue dependencies..."
          if grep -q '"vue"' package.json; then
            echo "Vue dependency found."
            echo "is-vue=true" >> $GITHUB_OUTPUT
          else
            echo "Vue not found."
            echo "is-vue=false" >> $GITHUB_OUTPUT
          fi

  vue-ci:
    name: Vue CI Workflow
    needs: detect-vue
    if: needs.detect-vue.outputs.is-vue == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run lint (optional)
        run: npm run lint || echo "Lint skipped"

      - name: Run tests (optional)
        run: npm run test:unit || echo "Tests skipped"

      - name: Build Vue App
        run: npm run build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: vue-dist
          path: dist/

